### ISSUE TITLE
Facing error. 'F' is not defined

### ISSUE THREAD

**Issue by Abhishek651** [htr-tech/indocrack#1]
[𝕳𝕿𝕽] Logging in ●●●●   [SUCCEED]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/data/data/com.termux/files/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "enc_file.py", line 25, in <module>
  File "<string>", line 1, in <module>
  File "tahm1d", line 5, in <module>
  File "<string>", line 4, in <module>
  File "tahm1d", line 12, in <module>
  File "<tahm1d>", line 2, in <module>
  File "<tahm1d>", line 1, in <module>
  File "<tahm1d>", line 18, in <module>
  File "", line 5, in <module>

  File "<string>", line 4, in <module>
  File "", line 12, in <module>

  File "<tahm1d>", line 2, in <module>
  File "<tahm1d>", line 2, in <module>
  File "<tahm1d>", line 2, in <module>
  File "<tahm1d>", line 2, in <module>
  File "<tahm1d>", line 2, in <module>
  File "<tahm1d>", line 1, in <module>
  File "<tahm1d>", line 19, in <module>
  File "<string>", line 1, in <module>
  File "<tahm1d>", line 115, in <module>
  File "<tahm1d>", line 67, in log
  File "<tahm1d>", line 88, in fog
  File "<tahm1d>", line 111, in dog
NameError: global name 'indohaxxx' is not defined
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/data/data/c
File "<tahm1d>", line 18, in <module>
  File "", line 5, in <module>

  File "<string>", line 4, in <module>
  File "", line 12, in <module>

  File "<tahm1d>", line 2, in <module>
  File "<tahm1d>", line 2, in <module>
  File "<tahm1d>", line 2, in <module>
  File "<tahm1d>", line 2, in <module>
  File "<tahm1d>", line 2, in <module>
  File "<tahm1d>", line 1, in <module>
  File "<tahm1d>", line 19, in <module>
  File "<string>", line 1, in <module>
  File "<tahm1d>", line 115, in <module>
  File "<tahm1d>", line 67, in log
  File "<tahm1d>", line 88, in fog
  File "<tahm1d>", line 111, in dog
NameError: global name 'indohaxxx' is not defined
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/data/data/com.termux/files/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "crack_enc.py", line 26, in <module>
  File "<string>", line 1, in <module>
  File "<tahm1d>", line 5, in <module>
  File "<string>", line 5, in <module>
NameError: name 'F' is not defined
$
$

**Comment by htr-tech** [comment]
@Abhishek651  update the tool .. remove the dir & install again
